import {Hero} from "../models/hero";

let count = 0;

export const heroes: Hero[] = [
  {id: count++, name: "AIRI", avatar: "0-AIRI.jpeg", isUsed: false, lane: ['DSL', 'JGL']},
  {id: count++, name: "ALEISTER", avatar: "1-ALEISTER.jpg", isUsed: false, lane: ['MID']},
  {id: count++, name: "ALICE", avatar: "2-ALICE.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "ALLAIN", avatar: "3-ALLAIN.jpg", isUsed: false, lane: ['DSL']},
  {id: count++, name: "AMILY", avatar: "4-AMILY.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "ANNETTE", avatar: "5-ANNETTE.png", isUsed: false, lane: ['ROAM', 'MID']},
  {id: count++, name: "AOI", avatar: "6-AOI.jpeg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "ARDUIN", avatar: "7-ARDUIN.png", isUsed: false, lane: ['DSL','ROAM']},
  {id: count++, name: "ARUM", avatar: "8-ARUM.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "ASTRID", avatar: "9-ASTRID.png", isUsed: false, lane: ['DSL','JGL']},
  {id: count++, name: "ATA", avatar: "10-ATA.jpg", isUsed: false, lane: ['DSL','ROAM']},
  {id: count++, name: "AYA", avatar: "11-AYA.jpg", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "AZZEN'KA", avatar: "12-AZZEN'KA.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "BALDUM", avatar: "13-BALDUM.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "BATMAN", avatar: "14-BATMAN.png", isUsed: false, lane: ['JGL']},
  {id: count++, name: "BRIGHT", avatar: "15-BRIGHT.jpg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "BUTTERFLY", avatar: "16-BUTTERFLY.jpeg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "CAPHENY", avatar: "17-CAPHENY.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "CELICA", avatar: "18-CELICA.jpg", isUsed: false, lane: ['ADL']},
  {id: count++, name: "CHAUGNAR", avatar: "19-CHAUGNAR.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "CRESHT", avatar: "20-CRESHT.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "D'ARCY", avatar: "21-D'ARCY.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "DEXTRA", avatar: "22-DEXTRA.jpg", isUsed: false, lane: ['DSL']},
  {id: count++, name: "DIAO CHAN", avatar: "23-DIAO CHAN.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "DIRAK", avatar: "24-DIRAK.jpg", isUsed: false, lane: ['MID']},
  {id: count++, name: "ELAND'ORR", avatar: "25-ELAND'ORR.jpg", isUsed: false, lane: ['JGL', "ADL"]},
  {id: count++, name: "ELSU", avatar: "26-ELSU.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "ENZO", avatar: "27-ENZO.jpeg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "ERROL", avatar: "28-ERROL.jpg", isUsed: false, lane: ['DSL']},
  {id: count++, name: "FENNIK", avatar: "29-FENNIK.png", isUsed: false, lane: ['JGL', 'ADL']},
  {id: count++, name: "FLORENTINO", avatar: "30-FLORENTINO.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "GILDUR", avatar: "31-GILDUR.png", isUsed: false, lane: ['ROAM', "DSL"]},
  {id: count++, name: "GRAKK", avatar: "32-GRAKK.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "HAYATE", avatar: "33-HAYATE.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "IGGY", avatar: "34-IGGY.jpeg", isUsed: false, lane: ['MID']},
  {id: count++, name: "IGNIS", avatar: "35-IGNIS.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "ILLUMIA", avatar: "36-ILLUMIA.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "ISHAR", avatar: "37-ISHAR.jpg", isUsed: false, lane: ['MID', 'ROAM']},
  {id: count++, name: "JINNA", avatar: "38-JINNA.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "KAHLII", avatar: "39-KAHLII.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "KEERA", avatar: "40-KEERA.jpg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "KIL'GROTH", avatar: "41-KIL'GROTH.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "KRIKNAK", avatar: "42-KRIKNAK.png", isUsed: false, lane: ['JGL']},
  {id: count++, name: "KRIXI", avatar: "43-KRIXI.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "KRIZZIX", avatar: "44-KRIZZIX.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "LAURIEL", avatar: "45-LAURIEL.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "LAVILLE", avatar: "46-LAVILLE.jpg", isUsed: false, lane: ['ADL']},
  {id: count++, name: "LILIANA", avatar: "47-LILIANA.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "LINDIS", avatar: "48-LINDIS.png", isUsed: false, lane: ['JGL','ADL']},
  {id: count++, name: "LORION", avatar: "49-LORION.jpg", isUsed: false, lane: ['MID']},
  {id: count++, name: "LU BU", avatar: "50-LU BU.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "LUMBURR", avatar: "51-LUMBURR.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "MALOCH", avatar: "52-MALOCH.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "MARJA", avatar: "53-MARJA.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "MAX", avatar: "54-MAX.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "MGANGA", avatar: "55-MGANGA.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "MINA", avatar: "56-MINA.png", isUsed: false, lane: ['DSL','ROAM']},
  {id: count++, name: "MOREN", avatar: "57-MOREN.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "MORTOS", avatar: "58-MORTOS.jpg", isUsed: false, lane: ['DSL']},
  {id: count++, name: "MURAD", avatar: "59-MURAD.png", isUsed: false, lane: ['JGL']},
  {id: count++, name: "NAKROTH", avatar: "60-NAKROTH.jpeg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "NATALYA", avatar: "61-NATALYA.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "OMEGA", avatar: "62-OMEGA.png", isUsed: false, lane: ['ROAM', 'DSL']},
  {id: count++, name: "OMEN", avatar: "63-OMEN.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "ORMARR", avatar: "64-ORMARR.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "PAINE", avatar: "65-PAINE.jpg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "PREYTA", avatar: "66-PREYTA.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "QI", avatar: "67-QI.png", isUsed: false, lane: ['DSL','JGL']},
  {id: count++, name: "QUILLEN", avatar: "68-QUILLEN.png", isUsed: false, lane: ['JGL']},
  {id: count++, name: "RAZ", avatar: "69-RAZ.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "RIKTOR", avatar: "70-RIKTOR.png", isUsed: false, lane: ['DSL', "ROAM"]},
  {id: count++, name: "ROUIE", avatar: "71-ROUIE.jpg", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "ROURKE", avatar: "72-ROURKE.png", isUsed: false, lane: ['JGL']},
  {id: count++, name: "ROXIE", avatar: "73-ROXIE.jpg", isUsed: false, lane: ['DSL']},
  {id: count++, name: "RYOMA", avatar: "74-RYOMA.png", isUsed: false, lane: ['DSL', "JGL"]},
  {id: count++, name: "SEPHERA", avatar: "75-SEPHERA.png", isUsed: false, lane: ['ROAM', "MID"]},
  {id: count++, name: "SINESTREA", avatar: "76-SINESTREA.jpg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "SKUD", avatar: "77-SKUD.png", isUsed: false, lane: ['DSL','JGL']},
  {id: count++, name: "SLIMZ", avatar: "78-SLIMZ.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "SUPERMAN", avatar: "79-SUPER MAN.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "TAARA", avatar: "80-TAARA.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "TACHI", avatar: "81-TACHI.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "TEEMEE", avatar: "82-TEEMEE.png", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "TEERI", avatar: "83-TEERI.jpg", isUsed: false, lane: ['ADL']},
  {id: count++, name: "TEL'ANNAS", avatar: "84-TEL'ANNAS.jpg", isUsed: false, lane: ['ADL']},
  {id: count++, name: "THANE", avatar: "85-THANE.png", isUsed: false, lane: ['ROAM', 'DSL']},
  {id: count++, name: "THE FLASH", avatar: "86-THE FLASH.png", isUsed: false, lane: ['JGL', "MID"]},
  {id: count++, name: "THE JOKER", avatar: "87-THE JOKER.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "THORNE", avatar: "88-THORNE.jpg", isUsed: false, lane: ['ADL']},
  {id: count++, name: "TORO", avatar: "89-TORO.png", isUsed: false, lane: ['ROAM', 'DSL']},
  {id: count++, name: "TULEN", avatar: "90-TULEN.png", isUsed: false, lane: ['MID']},
  {id: count++, name: "VALHEIN", avatar: "91-VALHEIN.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "VEERA", avatar: "92-VEERA.jpg", isUsed: false, lane: ['MID']},
  {id: count++, name: "VERES", avatar: "93-VERES.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "VIOLET", avatar: "94-VIOLET.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "VOLKATH", avatar: "95-VOLKATH.jpg", isUsed: false, lane: ['DSL','JGL']},
  {id: count++, name: "WIRO", avatar: "96-WIRO.png", isUsed: false, lane: ['ROAM', 'DSL']},
  {id: count++, name: "WISP", avatar: "97-WISP.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "WONDER WOMAN", avatar: "98-WONDER WOMAN.png", isUsed: false, lane: ['DSL']},
  {id: count++, name: "WUKONG", avatar: "99-WUKONG.jpg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "XENIEL", avatar: "100-XENIEL.png", isUsed: false, lane: ['DSL','ROAM']},
  {id: count++, name: "Y'BNETH", avatar: "101-Y'BNETH.png", isUsed: false, lane: ['ROAM','DSL']},
  {id: count++, name: "YAN", avatar: "102-YAN.jpg", isUsed: false, lane: ['JGL','DSL']},
  {id: count++, name: "YENA", avatar: "103-YENA.jpeg", isUsed: false, lane: ['DSL']},
  {id: count++, name: "YORN", avatar: "104-YORN.png", isUsed: false, lane: ['ADL']},
  {id: count++, name: "YUE", avatar: "105-YUE.jpg", isUsed: false, lane: ['MID']},
  {id: count++, name: "ZANIS", avatar: "106-ZANIS.png", isUsed: false, lane: ['JGL','DSL']},
  {id: count++, name: "ZATA", avatar: "107-ZATA.jpg", isUsed: false, lane: ['MID']},
  {id: count++, name: "ZEPHYS", avatar: "108-ZEPHYS.jpg", isUsed: false, lane: ['JGL']},
  {id: count++, name: "ZILL", avatar: "109-ZILL.png", isUsed: false, lane: ['JGL']},
  {id: count++, name: "ZIP", avatar: "110-ZIP.jpeg", isUsed: false, lane: ['ROAM']},
  {id: count++, name: "ZUKA", avatar: "111-ZUKA.png", isUsed: false, lane: ['DSL','JGL']},
  {id: count++, name: "BONNIE", avatar: "112-BONNIE.jpg", isUsed: false, lane: ['MID']},
  {id: count++, name: "BIJAN", avatar: "113-BIJAN.jpg", isUsed: false, lane: ['DSL']},
  {id: count++, name: "HELEN", avatar: "114-HELEN.jpg", isUsed: false, lane: ['ROAM']}
]
